spring:
  profiles:
    active: local
  config:
    import:
      - optional:application-secret-${spring.profiles.active}.yaml
  application:
    name: spring4-bestpractice
  docker:
    compose:
      enabled: false

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

springdoc:
  swagger-ui:
    path: /swagger

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"