-- PostgreSQL 호환 users 테이블 생성 DDL 스크립트
-- JPA Entity와의 완벽한 정합성을 보장하기 위해 논리형 컬럼 타입을 BOOLEAN으로 정의합니다.

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL,
    employee_num VARCHAR(20),
    dept_name VARCHAR(100),
    role VARCHAR(20) NOT NULL DEFAULT 'GUEST',
    permissions JSONB,
    sso_id VARCHAR(100) UNIQUE,
    knox_user_id VARCHAR(100) UNIQUE,
    approval_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    is_auto_approved BOOLEAN NOT NULL DEFAULT FALSE, -- BOOLEAN 타입으로 변경
    approved_by BIGINT REFERENCES users(user_id),
    approved_at TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE, -- BOOLEAN 타입으로 변경
    last_login_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    privacy_agreed BOOLEAN NOT NULL DEFAULT FALSE, -- BOOLEAN 타입으로 변경
    privacy_agreed_at TIMESTAMP,
    privacy_policy_version VARCHAR(20),
    is_withdrawn BOOLEAN NOT NULL DEFAULT FALSE, -- BOOLEAN 타입으로 변경
    withdrawn_at TIMESTAMP,
    withdrawal_reason VARCHAR(500)
);

-- 가독성 및 조회 최적화를 위한 주요 식별자 인덱스 추가
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_sso_id ON users(sso_id);
CREATE INDEX IF NOT EXISTS idx_users_knox_user ON users(knox_user_id);
CREATE INDEX IF NOT EXISTS idx_users_dept ON users(dept_name);
